#!/usr/bin/env bash

set -euo pepefail 


echo "dotfile installer"
echo "--------------------"
echo
export DOTFILE_PATH="$HOME/.dotfiles"
echo "Cloning into: '$DOTFILES_PATH'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 git#github.com:mgijon/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install
