#!/usr/bin/env bash
set -euo pepefail

echo "dotfile installer"
echo "--------------------"
echo
export DOTFILE_PATH="$HOME/.dotfiles"
echo "Cloning into: '$DOTFILES_PATH'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 git#github.com:mgijon/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Python
brew install python
# PyCharm
brew install --cask pycharm
# R
 brew install --cask r #brew install r
# R Studio
brew install --cask rstudio
# Docker
brew install docker
# FZF
brew install fzf
brew upgrade fzf
# Graphviz
brew install graphviz
# Postgres
brew install postgresql

# Firefox
brew install --cask firefox
# Google Chrome
brew install --cask google-chrome
# Thunderbird
brew install --cask thunderbird
# Telegram
brew install --cask telegram
# Discord
brew install --cask discord
# Skype
brew install --cask skype
# Slack
brew install --cask slack
# Obs Stream
brew install --cask obs

# Dropbox
brew install --cask dropbox
# Kindle
brew install --cask kindle

# Atom
brew install --cask atom
# Visual Studio Code
brew install --cask visual-studio-code

# Deezer
brew install --cask deezer
# Postman
brew install --cask postman
# Musescore
brew install --cask musescore

#
brew install gpg pinentry-mac

## Install Vundle
sudo git clone https://github.com/gmarik/vundle.git $HOME\vimfiles\bundle\vundle
# y luego la password para hacerlo funcionar

# Install recursive grep
brew install ripgrep
# If it does not work, I've already use in the past the installation using cargo: $ cargo install ripgrep
