name: Check Python scripts

on:
  push:
    branches: [main]
    paths:
      - scripts/**.py
  pull_requests:
    branches: [main]
    paths:
      - scripts/**.py

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run type checks
        # stop the building if the type checking is not properly done
        run: |
          mypy . --exclude libraries
    - name: Run linting
        # stop the building if the files has not been properly formatted
        run: | 
          black . --check --verbose
    - name: Test with pytest
      run: |
        # stop the process if some of the tests fails
        pytest scripts/ 
